# Generated by Django 3.0.8 on 2020-08-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='auction_listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction_listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
