# Generated by Django 3.0.8 on 2020-08-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200809_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction_listings',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.Auction_listing'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='auction_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_listing', to='auctions.Auction_listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='currentUser',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currentUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
