# Generated by Django 3.0.8 on 2020-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200809_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auction_listings',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item', to='auctions.Auction_listing'),
        ),
    ]
