# Generated by Django 3.0.8 on 2020-08-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200813_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1024, upload_to=''),
        ),
    ]
