# Generated by Django 3.0.8 on 2020-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200813_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='starting_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
