# Generated by Django 3.0.8 on 2020-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200814_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
