# Generated by Django 3.0.8 on 2020-08-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200814_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image_url',
            field=models.ImageField(blank=True, default='https://thumbs.dreamstime.com/b/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132482930.jpg', max_length=1024, upload_to=''),
        ),
    ]
